export const CHARACTER_BANKS = {
  global: {
    traits: [
      "Calm under cascading pressure",
      "Absorbs chaos and returns clarity",
      "Reads morale shifts before anyone speaks them aloud",
      "Turns panic into procedure",
      "Curiosity sharp enough to feel dangerous",
      "Balances awe with disciplined observation",
      "Most comfortable at the edge of the risk envelope",
      "Keeps calm when the environment turns violent",
      "Finds structure in noise before anyone else notices the pattern",
      "Most confident when the alarm stack is overflowing",
    ],
    flaws: [
      "Carries too much alone before delegating",
      "Can mistake control for safety",
      "Pushes forward before consensus fully forms",
      "Pushes damaged systems long past the safe window",
      "Cuts safety margins too aggressively under time pressure",
      "Can chase understanding past the point of safety",
      "Hides how personally invested they become in unexplained phenomena",
      "Understates injuries if the mission still has momentum",
      "Takes on the highest-risk task by reflex",
      "Treats pain like irrelevant background data",
    ],
  },
  commander: {
    names: [
      "Commander Alma Vasquez",
      "Commander Elias Ward",
      "Commander Nadiya Sato",
      "Commander Jonah Mercer",
    ],
    callSigns: ["Aegis", "Bulwark", "Anchor", "Northstar", "Sentinel"],
    specialties: [
      "Command tempo and crisis triage",
      "Battlefield delegation and emergency route planning",
      "Crew stabilization and mission reprioritization",
      "Operational tempo and high-risk command timing",
      "Cross-discipline decision control under signal loss",
    ],
    stakes: [
      "Will not lose another mission under their command",
      "Refuses to let another crew disappear under their watch",
      "Needs this mission to prove they can lead in deep-field isolation",
      "Believes hesitation is what killed a previous mission partner",
      "Needs to bring every crew member home to justify one brutal call years ago",
    ],
  },
  flight_engineer: {
    names: [
      "Chief Engineer Tunde Okafor",
      "Chief Engineer Mara Venn",
      "Chief Engineer Iker Alvarez",
      "Chief Engineer Selene Brooks",
    ],
    callSigns: ["Patchbay", "Sparkwell", "Fuse", "Weld", "Relay"],
    specialties: [
      "Life support stabilization and field repair",
      "Power routing and improvised hardware salvage",
      "Life support repair and subsystem triage",
      "Pressure seal recovery and thermal control repair",
      "Redundant systems management under cascading faults",
    ],
    stakes: [
      "Knows the rover only gets one real failure before people start dying",
      "Built half this rover and refuses to watch it die in silence",
      "Needs to prove the maintenance doctrine they wrote actually works in the field",
      "Won't return home as the engineer who lost the air loop",
      "Needs this mission to validate years spent defending risky hardware upgrades",
    ],
  },
  science_officer: {
    names: [
      "Dr. Imani Reyes",
      "Dr. Leena Volkov",
      "Dr. Mateo Quinn",
      "Dr. Safiya Noor",
    ],
    callSigns: ["Spectra", "Prism", "Cipher", "Halo", "Lattice"],
    specialties: [
      "Signal analysis and anomaly interpretation",
      "Signal decoding and anomaly modeling",
      "Telemetry synthesis and buried-data reconstruction",
      "Lunar geology correlation and exotic pattern detection",
      "Pattern analysis across corrupted telemetry fields",
    ],
    stakes: [
      "Believes this signal could redefine humanity's place on the moon",
      "Needs this find to vindicate a theory the program mocked for years",
      "Believes this signal could redeem a career damaged by one bad call",
      "Needs proof that the moon still holds something no one else has seen",
      "Needs this anomaly to be real enough to justify a lifetime of obsession",
    ],
  },
  mission_specialist: {
    names: [
      "Lt. Hana Park",
      "Lt. Darius Cole",
      "Lt. Mireya Santos",
      "Lt. Owen Hale",
    ],
    callSigns: ["Waypoint", "Latch", "Vector", "Spindle", "Torch"],
    specialties: [
      "EVA deployment and field improvisation",
      "Surface traversal and emergency field extraction",
      "Relay deployment and improvised surface rigging",
      "Airlock breach response and EVA improvisation",
      "Surface hazard response under comms degradation",
    ],
    stakes: [
      "Needs this mission to prove the last surface accident was not a career-ending failure",
      "Needs a clean mission after the EVA loss that still follows them",
      "Wants this operation to erase the label of liability from their record",
      "Needs this mission to prove they still belong outside the airlock",
      "Needs one flawless field op before command buries them behind a desk",
    ],
  },
};
